let info = [
{
	"id": 1,
	"title": "Marketing",
	"url": "digital-marketing-banner-12x8-revised-01.png",	
	"desc": "Marketing refers to activities a company undertakes to promote the buying or selling of a product or service. Marketing includes advertising, selling, and delivering products to consumers or other businesses. ",
	"cat": 'marketing',
	"lection":'2 лекции',
	'hash1': '#1',
	'img1':'shopping-bags_1f6cd.png',
	'link1':'https://www.udemy.com/course/digital-marketing-masterclass/',
	'lection1title' : 'Digital Marketing Masterclass',
	'lection1desc': 'You re looking for a complete digital marketing course to teach you everything you need to become a digital marketing expert, right?',
	'hash2': '#2',
	'img2': 'shopping-cart_1f6d2.png',
	'link2':'https://www.udemy.com/course/facebook-ads-facebook-marketing-mastery-guide/',
	'lection2title' : 'Facebook Ads & Facebook Marketing MASTERY 202',
	'lection2desc': 'Want to become a Facebook Ads expert? JOIN THE 500+ COMPANIES I HAVE CONSULTED ON SOCIAL MEDIA MARKETING AND INCREASED CONVERSIONS FOR VIA FACEBOOK AND INSTAGRAM ADS! Facebook Marketing is a REQUIRED skill for anyone with a business, product, service, brand, or public figure they need to PROMOTE! Join our 300,000+ modMBA students who have MASTERED Facebook advertising with this COMPLETE Facebook Marketing Mastery Course!',	
},
{
	"id": 2,
	"title": "Business",	
	"url": "best-business-ideas-post-coronavirus.jpg",
	"desc": "Business is the activity of making one's living or making money by producing or buying and selling products (such as goods and services). Simply put, it is any activity or enterprise entered into for profit.",
	"cat": 'business',
	"lection":'2 лекции',
	'hash1': '#1',
	'img1':'chart-increasing_1f4c8.png',
	'link1':'https://www.udemy.com/course/the-complete-business-plan-course/',
	'lection1title' : 'The Complete Business Plan Course',
	'lection1desc': 'Welcome to the Complete Business Plan Course, which will help you make an incredible business plan from scratch. Everything that you need to make your awesome business plan is included in this course, including 50 business plan templates and an incredibly detailed 13 step process to help you make an entire business plan from scratch!',
	'hash2': '#2',
	'img2':'factory_1f3ed.png',
	'link2':'https://www.udemy.com/course/agile-strategy-execution/',
	'lection2title' : 'Business Strategy Execution: The Agile/Lean Way',
	'lection2desc': 'Your business success is not merely having a goal, a direction, a strategy. It is the ability to create the process, the organization, the capabilities and culture, the result in performance toward that strategy. This course is a roadmap that will enable you to successfully execute strategy.',	
	
},
{
	"id": 3,
	"title": "UI/UX",	
	"url": 'Web_UI_UX.original.png',
	"desc": "User interface design or user interface engineering is the design of user interfaces for machines and software, such as computers, home appliances, mobile devices, and other electronic devices, with the focus on maximizing usability and the user experience The goal of user interface design is to make the user's interaction as simple and efficient as possible, in terms of accomplishing user goals.",
	"cat": 'ux',
	'lection':'2 лекции',
	'hash1': '#1',
	'img1':'rocket_1f680.png',
	'link1':'https://www.udemy.com/course/ui-ux-web-design-using-adobe-xd/',
	'lection1title' : 'User Experience Design Essentials - Adobe XD UI UX Design',
	'lection1desc': 'Are you excited to get into the world of UI/UX but you dont know where to start? This course will allow you to add UX designer to your CV & start getting paid for your new skills.',
	'hash2': '#2',
	'img2':'gear_2699.png',
	'link2':'https://www.udemy.com/course/adobexd-webdesign/',
	'lection2title' : 'Learn Adobe Xd Webdesign: Design websites from zero: UX & UI',
	'lection2desc': 'The problem with designing websites in older design tools (like Photoshop or Illustrator) is that these tools dont have the features that UX/UI designers really need to help them designing websites. Like working with color pallets, font style guides and repeating elements. Or things like sharing your work via prototypes. These old software tools are also not vector, which can be an issue for development.',
},
{
	"id": 4,
	"title": "Design",	
	"url": '7cbf402ac7fb9ae58f37b22227a63a9f.png',
	"desc": "A design is a plan or specification for the construction of an object or system or for the implementation of an activity or process, or the result of that plan or specification in the form of a prototype, product or process. The verb to design expresses the process of developing a design .",
	"cat": 'design',	
	'lection':'2 лекции',
	'hash1': '#1',
	'img1':'light-bulb_1f4a1.png',
	'link1':'https://www.udemy.com/course/graphic-design-theory-for-beginners-course/',
	'lection1title' : 'The Complete Graphic Design Theory for Beginners Course',	
	'hash2': '#2',
	'img2':'notebook_1f4d3.png',
	'lection1desc': 'Learn Graphic Design Theory in this New Course! Many people want to become designers but dont know the basic fundamentals of design at all.It can takes years to piece together different ideas to truly begin to understand how it even works.but it doesnt have to be like that.	By understanding the foundations of color, typography, layout, composition, branding, and other fields of study in the graphic design realm, you can propel yourself from a beginner to an expert, just by having the right education.',
	'link2':'https://www.udemy.com/course/designit-design-thinking/',
	'lection2title' : 'Design Thinking in 3 Steps',
	'lection2desc': 'In this course, you’ll learn design thinking from the people who helped invent it. Designit is a global strategic design firm, and our designers help organizations across the globe learn and adopt a human-centered approach to innovation.This course is taught by Alan Cooper, Sanskriti Ayyar, and Teresa Brazen, team members from Cooper Professional Education (CPE) — a team at Designit.	Through this interactive course, you’ll learn a different approach to strategic problem solving so that you can create experiences customers love. You’ll practice design thinking on a real-life project and equip yourself with a powerful set of tools to become more collaborative, innovative, and effective.',
	
},
{
	"id": 5,
	"title": "Data Science",	
	"url": 'preview.jpg',
	"desc": "Data science is an inter-disciplinary field that uses scientific methods, processes, algorithms and systems to extract knowledge and insights from many structural and unstructured data. Data science is related to data mining, machine learning and big data.",
	"cat": 'data-science',
	'lection':'2 лекции',
	'hash1': '#1',
	'img1':'bar-chart_1f4ca.png',
	'link1':'https://www.udemy.com/course/the-data-science-course-complete-data-science-bootcamp/',
	'lection1title' : 'The Data Science Course 2020: Complete Data Science Bootcamp',
	'hash2': '#2',	
	'img2':'satellite-antenna_1f4e1.png',
	'lection1desc': 'Data scientist is one of the best suited professions to thrive this century. It is digital, programming-oriented, and analytical. Therefore, it comes as no surprise that the demand for data scientists has been surging in the job marketplace.However, supply has been very limited. It is difficult to acquire the skills necessary to be hired as a data scientist. And how can you do that? Universities have been slow at creating specialized data science programs. (not to mention that the ones that exist are very expensive and time consuming) Most online courses focus on a specific topic and it is difficult to understand how the skill they teach fit in the complete picture  ',
	'link2':'https://www.udemy.com/course/machinelearning/',
	'lection2title' : 'Machine Learning A-Z™: Hands-On Python & R In Data Science',
	'lection2desc': 'Interested in the field of Machine Learning? Then this course is for you! This course has been designed by two professional Data Scientists so that we can share our knowledge and help you learn complex theory, algorithms, and coding libraries in a simple way.We will walk you step-by-step into the World of Machine Learning. With every tutorial, you will develop new skills and improve your understanding of this challenging yet lucrative sub-field of Data Science.',
},
{
	"id": 6,
	"title": "Programming",
	"url": 'illustration-programmer-working-his-desk_23-2148270201.jpg',	
	"desc": "Computer programming is the process of designing and building an executable computer program to accomplish a specific computing result or to perform a specific task. Programming involves tasks such as: analysis, generating algorithms, profiling algorithms' accuracy and resource consumption,and the implementation algorithms.",
	"cat": 'programming',
	'lection':'2 лекции',
	'hash1': '#1',
	'img1':'keyboard_2328.png',
	'link1':'https://www.udemy.com/course/the-ultimate-python-programming-course/',
	'lection1title' : 'The Ultimate Python Programming Tutorial',
	'hash2': '#2',
	'img2':'laptop_1f4bb.png',
	'lection1desc': 'In this online Python course from OReilly Media, you will learn how to program with the popular development language. This tutorial is designed for the beginner, and you do not need to have any experience at all with programming or development in order to learn how to program with Python using this video tutorial.',
	'link2':'https://www.udemy.com/course/javascript-the-complete-guide-2020-beginner-advanced/',
	'lection2title' : 'JavaScript - The Complete Guide 2020 (Beginner + Advanced)',
	'lection2desc': 'JavaScript is THE most important programming language you need to learn as a web developer - and with this course, you make sure that you will not miss a single thing you have to know as a JavaScript developer!	This is the most comprehensive and modern course you can find on JavaScript - its based on all my JavaScript knowledge AND teaching experience. Its both a complete guide, starting with the core basics of the language, as well as an extensive reference of the JavaScript language and environment, ensuring that both newcomers as well as experienced JavaScript developers get a lot out of this course!',
}]

export default info;